[app]
title = Trading Bot
package.name = tradingbot
package.domain = org.tradingbot
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0.0
requirements = python3,kivy,yfinance,requests
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.1.0
fullscreen = 0
android.permissions = INTERNET, WAKE_LOCK, FOREGROUND_SERVICE
android.api = 30
android.minapi = 21
android.ndk = 23b
android.sdk = 30
android.archs = arm64-v8a, armeabi-v7a
android.entitlement = true
